### ISSUE TITLE
Implement `serde` for `Bytes64`

### ISSUE THREAD

**Issue by vlopes11** [FuelLabs/fuel-types#13]
Serde requires a manual implementation for `[u8; 64]`.

https://github.com/FuelLabs/fuel-types/blob/03148852d7a0c335fc335cb15305b9afe5871da2/src/types.rs#L47

`serde` implementation is expected for all types of this crate.

**Comment by Dentosal** [comment]
[serde_big_array crate](https://docs.rs/serde-big-array/latest/serde_big_array/) can be used for this

**Comment by eureka-cpu** [comment]
> [serde_big_array crate](https://docs.rs/serde-big-array/latest/serde_big_array/) can be used for this

oo nice, ty
