### ISSUE TITLE
Feature `edition2021` is required on Fresh Ubuntu Install

### ISSUE THREAD

**Issue by ControlCplusControlV** [FuelLabs/fuel-types#18]
Was actually testing the curl dependence on a fresh install of Ubuntu 20.04 LTS and after the following commands

- sudo apt update && sudo apt upgrade
- sudo apt install cargo
- cargo install forc

When I encountered 

```
error: failed to compile `forc v0.2.1`, intermediate artifacts can be found at `/tmp/cargo-installuiNuOQ`

Caused by:
  failed to parse manifest at `/home/controlc/.cargo/registry/src/github.com-1ecc6299db9ec823/fuel-types-0.1.0/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest 
```

Testing the recommended remedy atm

**Comment by Voxelot** [comment]
This is likely a sway issue: https://github.com/FuelLabs/sway/blob/master/forc/Cargo.toml#L5

**Comment by ControlCplusControlV** [comment]
Was actually due to not setting

```
rustup default stable
```

Closing this issue as that is recommended there, although adding as a warning or similar on forc's cargo page could be worth it.
